#!/bin/sh
set -e

case "$1" in
  configure)
    # For systemd, enable the rest-mail unit, but don't start it (just like the
    # init script).
    if [ -x /bin/systemctl ]; then
      systemctl enable rest-mail.service >/dev/null 2>&1 || true
    fi
    ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

# Automatically added by dh_installinit
if [ -x "/etc/init.d/rest-mail" ] || [ -e "/etc/rest-mail/config.cfg" ]; then
        if [ ! -e "/etc/init/rest-mail.conf" ]; then
                update-rc.d rest-mail defaults 16 80 >/dev/null
        fi
        invoke-rc.d rest-mail start || exit $?
fi
# End automatically added section


exit 0
