#!/bin/sh
set -e

# systemd: reload the daemon
if [ -x /bin/systemctl ]; then
  systemctl daemon-reload >/dev/null 2>&1 || true
fi

case "$1" in
  upgrade)
    # systemd: start the new version of rest-mail
    if [ -x /bin/systemctl ]; then
      systemctl restart rest-mail.service
    fi
    ;;

  purge)
    deluser rest-mail
	rm -rf /run/rest-mail
    ;;

  remove|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
        update-rc.d rest-mail remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
        systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


exit 0
